package interpreter;

import generation.deutschsprachigeProgrammierspracheBaseVisitor;
import generation.deutschsprachigeProgrammierspracheParser;
import model.*;

import java.util.ArrayList;
import java.util.List;

/**
 * Visits the parse tree generated by ANTLR and converts each parsed
 * instruction into the corresponding instruction object.
 * The resulting program lines are stored for later interpretation.
 */
public class ProgramVisitor extends deutschsprachigeProgrammierspracheBaseVisitor<Void> {

    private List<ProgramLine> programLines = new ArrayList<>();

    public ProgramVisitor() {
    }

    /**
     * Visits a numbered program line, creates the corresponding instruction
     * objects and stores them as ProgramLines.
     *
     * @param ctx the parse tree context of a numbered program line
     * @return null
     */
    @Override
    public Void visitZeilenNummerierung(deutschsprachigeProgrammierspracheParser.ZeilenNummerierungContext ctx) {
        int lineNumber = Integer.parseInt(ctx.zeilenReferenzierung().NUMBER().getText());
        for (deutschsprachigeProgrammierspracheParser.AnweisungContext anweisungContext : ctx.anweisung()) {
            programLines.add(new ProgramLine(lineNumber, createInstruction(anweisungContext)));
        }
        return null;
    }

    public List<ProgramLine> getProgramLines() {
        return programLines;
    }

    /**
     * Creates the corresponding instruction object for a parsed instruction.
     *
     * @param ctx the parse tree context of an instruction
     * @return the created instruction
     * @throws IllegalArgumentException if the instruction type is unknown
     */
    private Instruction createInstruction(deutschsprachigeProgrammierspracheParser.AnweisungContext ctx) {
        if (ctx.intergerDeklaration() != null) {
            return new AssignmentInstruction(
                    ctx.intergerDeklaration().ALPHANUMERIC().getText(),
                    Integer.parseInt(ctx.intergerDeklaration().NUMBER().getText())
            );
        }

        if (ctx.wertzuweisungAddition() != null) {
            return new AdditionInstruction(
                    ctx.wertzuweisungAddition().ALPHANUMERIC(0).getText(),
                    ctx.wertzuweisungAddition().ALPHANUMERIC(1).getText(),
                    ctx.wertzuweisungAddition().ALPHANUMERIC(2).getText()
            );
        }

        if (ctx.wertzuweisungSubtraktion() != null) {
            return new SubtractionInstruction(
                    ctx.wertzuweisungSubtraktion().ALPHANUMERIC(0).getText(),
                    ctx.wertzuweisungSubtraktion().ALPHANUMERIC(1).getText(),
                    ctx.wertzuweisungSubtraktion().ALPHANUMERIC(2).getText()
            );
        }

        if (ctx.sprunganweisung() != null) {
            if (ctx.sprunganweisung().unbedingteSprunganweisung() != null) {
                return new UnconditionalJumpInstruction(Integer.parseInt(ctx.sprunganweisung().unbedingteSprunganweisung().zeilenReferenzierung().NUMBER().getText()));
            } else if (ctx.sprunganweisung().bedingteSprunganweisung() != null) {
                return new ConditionalJumpInstruction(
                        ctx.sprunganweisung().bedingteSprunganweisung().ALPHANUMERIC().getText(),
                        Integer.parseInt(ctx.sprunganweisung().bedingteSprunganweisung().NUMBER().getText()),
                        Integer.parseInt(ctx.sprunganweisung().bedingteSprunganweisung().zeilenReferenzierung().NUMBER().getText())
                );
            }
        }

        if (ctx.stopAnweisung() != null) {
            return new StopInstruction();
        }

        if (ctx.ausgabe() != null) {
            return new OutputInstruction(ctx.ausgabe().ALPHANUMERIC().getText());
        }

        if (ctx.eingabe() != null) {
            return new InputInstruction(ctx.eingabe().ALPHANUMERIC().getText());
        }

        throw new IllegalArgumentException("Unknown instruction: " + ctx.getText());
    }
}
